apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-bridge-data
  labels:
    app: project-bridge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
