apiVersion: v1
kind: Service
metadata:
  name: project-bridge
  labels:
    app: project-bridge
spec:
  type: NodePort
  selector:
    app: project-bridge
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 32200
      protocol: TCP
